=== krissisavova/GuitarCatalog/GuitarsCatalog/GuitarsCatalog.dtd
<?xml version="1.0" encoding="UTF-8" ?>

        <!-- ELEMENTS -->
        <!ELEMENT guitars_catalog (guitars+)>
        <!ELEMENT guitars (mainInfo*, descriptions*, guitarAbout*, productDetails*, guitar*)>

        <!ELEMENT guitar (brand, image?, company_name?, rating?)>
        <!ELEMENT brand (#PCDATA)>
        <!ELEMENT image (#PCDATA)>
        <!ELEMENT company_name (#PCDATA)>
        <!ELEMENT rating (#PCDATA)>

        <!ELEMENT mainInfo (guitar, type, color, orientation, num_of_strings, cost)>
        <!ELEMENT type (#PCDATA)> <!-- acoustic, electric, bass, ukulele, middle-sized guitar -->
        <!ELEMENT color (#PCDATA)>
        <!ELEMENT orientation (#PCDATA)>
        <!ELEMENT num_of_strings (#PCDATA)>
        <!ELEMENT cost (#PCDATA)>

        <!ELEMENT descriptions (guitar, description)>
        <!ELEMENT description (#PCDATA)>

        <!ELEMENT guitarAbout (guitar, countryOfOrigin, yearOfManufacture, website)>
        <!ELEMENT countryOfOrigin (#PCDATA)>
        <!ELEMENT yearOfManufacture (#PCDATA)>
        <!ELEMENT website (#PCDATA)>

        <!ELEMENT productDetails (guitar, series, fingerboard_material, amount, condition, comingWith?)>
        <!ELEMENT series (#PCDATA)>
        <!ELEMENT fingerboard_material (#PCDATA)>
        <!ELEMENT amount (#PCDATA)>
        <!ELEMENT condition (#PCDATA)>
        <!ELEMENT comingWith (#PCDATA)>

        <!-- ATTRIBUTES -->
        <!ATTLIST type category CDATA #REQUIRED>
        <!ATTLIST orientation hand CDATA #REQUIRED> <!-- left / right -->
        <!ATTLIST series guitarId CDATA #REQUIRED>
        <!ATTLIST productDetails isAvailable (Да|Не) "Не">
        <!ATTLIST cost currency CDATA #REQUIRED>
        <!ATTLIST countryOfOrigin code CDATA #REQUIRED>

=== krissisavova/GuitarCatalog/GuitarsCatalog/Guitars-2.xml
<?xml version = "1.0" encoding = "UTF-8"?>

<?xml-stylesheet type="text/xsl" href="html-transformation-2.xsl"?>

<!DOCTYPE guitars_catalog SYSTEM "GuitarsCatalog.dtd">

<guitars_catalog>
<guitars>

    <descriptions>
        <guitar>
            <brand> Fender Squier Affinity Series Stratocaster </brand>
            <image> fender-olympic-white.jpg </image>
        </guitar>
        <description>
            Fender Squier Affinity Stratocaster е невероятно популярен поради доброто си качество на изработката.
            Когато става въпрос за електрически китари, качеството на пикапите (pickups) играе най-голяма роля в качеството на тона на китарата.
            Ако сте начинаещ, който започва да се занимава сериозно с китара, тогава Fender Squier Affinity би бил добър избор за Вас.
        </description>
    </descriptions>

    <descriptions>
        <guitar>
            <brand> Ibanez Cosmic Shadow </brand>
            <image> ibanez-black.jpg </image>
        </guitar>
        <description>
            Изработена с олекотен корпус от махагон и шия от 5 части клен/венге, тази китара се отличава с резонансен тон, който няма да ви тежи.
        </description>
    </descriptions>

    <descriptions>
        <guitar>
            <brand> Takamine GD51 Brown Sunburst </brand>
            <image> takamine.jpg </image>
        </guitar>
        <description>
            Готов за всяка ситуация на изпълнение, този модел се отличава с масивна горна част от смърч и черен орех отзад и отстрани, които произвеждат хубав и мощен звук.
        </description>
    </descriptions>

    <descriptions>
        <guitar>
            <brand> Framus FD Vintage </brand>
            <image> framus.jpg </image>
        </guitar>
        <description>
            Тази китара е перфектният избор както за начинаещи, така и за напреднали музиканти.
            Моделът е рядък, но изработен с висококачествени материали, което допринася и за нейния изчистен звук.
        </description>
    </descriptions>

    <descriptions>
        <guitar>
            <brand> Sire Marcus Miller V5 Alder-5 Натурал </brand>
            <image> bass-sire.jpg </image>
        </guitar>
        <description>
            Това е автентична джаз бас китара.
            За тези, които харесват лек бас и не обичат сложните настройки, това е много прост модел с прости настройки на звука.
            Идеална за начинаещи.
        </description>
    </descriptions>

    <descriptions>
        <guitar>
            <brand> Arrow MH-10 Концертно укулеле Натурал </brand>
            <image> ukulele.jpg </image>
        </guitar>
        <description>
            Моделът ARROW MH10 Concert Mahogany е укулеле с изящна изработка. Съставен е от най-добрите компоненти и се характеризира с мелодичен звук и интересен дизайн.
            Идеален за ежедневно свирене при всякакви условия, където и да се намирате.
        </description>
    </descriptions>

</guitars>
</guitars_catalog>

=== krissisavova/GuitarCatalog/GuitarsCatalog/Guitars-5.xml
<?xml version = "1.0" encoding = "UTF-8"?>

<?xml-stylesheet type="text/xsl" href="html-transformation-4.xsl"?>

<!DOCTYPE guitars_catalog SYSTEM "GuitarsCatalog.dtd">

<!--> The most popular guitars from the collection (rating > 4.5) -->

<guitars_catalog>
    <guitars>
        <guitar>
            <brand> Fender Squier Affinity Series Stratocaster </brand>
            <image> fender-olympic-white.jpg </image>
            <company_name> Fender </company_name>
            <rating> 4.8 </rating>
        </guitar>
        <guitar>
            <brand> Ibanez Cosmic Shadow </brand>
            <image> ibanez-black.jpg </image>
            <company_name> Ibanez </company_name>
            <rating> 4.6 </rating>
        </guitar>
        <guitar>
            <brand> Takamine GD51 Brown Sunburst </brand>
            <image> takamine.jpg </image>
            <company_name> Takamine </company_name>
            <rating> 4.1 </rating>
        </guitar>
        <guitar>
            <brand> Framus FD Vintage </brand>
            <image> framus.jpg </image>
            <company_name> Framus Vintage </company_name>
            <rating> 4.7 </rating>
        </guitar>
        <guitar>
            <brand> Sire Marcus Miller V5 Alder-5 Натурал </brand>
            <image> bass-sire.jpg </image>
            <company_name> Sire </company_name>
            <rating> 4.3 </rating>
        </guitar>
        <guitar>
            <brand> Arrow MH-10 Концертно укулеле Натурал </brand>
            <image> ukulele.jpg </image>
            <company_name> Arrow </company_name>
            <rating> 4.5 </rating>
        </guitar>
    </guitars>
</guitars_catalog>

=== krissisavova/GuitarCatalog/GuitarsCatalog/Guitars-1.xml
<?xml version = "1.0" encoding = "UTF-8"?>

<?xml-stylesheet type="text/xsl" href="html-transformation-1.xsl"?>

<!DOCTYPE guitars_catalog SYSTEM "GuitarsCatalog.dtd">

<guitars_catalog>
    <guitars>
        <mainInfo>
            <guitar>
                <brand> Fender Squier Affinity Series Stratocaster </brand>
                <image>fender-olympic-white.jpg</image>
            </guitar>
            <type category="Електрическа" />
            <color> Бяла </color>
            <orientation hand="За дясна ръка" />
            <num_of_strings> 6 струни </num_of_strings>
            <cost currency="BGN"> 490 </cost>
        </mainInfo>
        
        <mainInfo>
            <guitar>
                <brand> Ibanez Cosmic Shadow </brand>
                <image> ibanez-black.jpg </image>
            </guitar>
            <type category="Електрическа" />
            <color> Черна </color>
            <orientation hand="За лява ръка" />
            <num_of_strings> 6 струни </num_of_strings>
            <cost currency="EUR"> 1915 </cost>
        </mainInfo>
        
        <mainInfo>
            <guitar>
                <brand> Takamine GD51 Brown Sunburst </brand>
                <image> takamine.jpg </image>
            </guitar>
            <type category="Акустична" />
            <color> Слънчево кафява </color>
            <orientation hand="За дясна ръка" />
            <num_of_strings> 6 струни </num_of_strings>
            <cost currency="BGN"> 600 </cost>
        </mainInfo>
        
        <mainInfo>
            <guitar>
                <brand> Framus FD Vintage </brand>
                <image> framus.jpg </image>
            </guitar>
            <type category="Електро-акустична" />
            <color> Натурал </color>
            <orientation hand="За лява ръка" />
            <num_of_strings> 12 струни </num_of_strings>
            <cost currency="EUR"> 460 </cost>
        </mainInfo>
        
        <mainInfo>
            <guitar>
                <brand> Sire Marcus Miller V5 Alder-5 Натурал </brand>
                <image> bass-sire.jpg </image>
            </guitar>
            <type category="Бас" />
            <color> Натурал </color>
            <orientation hand="За дясна ръка" />
            <num_of_strings> 5 струни </num_of_strings>
            <cost currency="USD"> 589 </cost>
        </mainInfo>

        <mainInfo>
            <guitar>
                <brand> Arrow MH-10 Концертно укулеле Натурал </brand>
                <image> ukulele.jpg </image>
            </guitar>
            <type category="Укулеле" />
            <color> Светлокафява </color>
            <orientation hand="За двете ръце" />
            <num_of_strings> 4 струни </num_of_strings>
            <cost currency="SEN"> 7700 </cost>
        </mainInfo>
    </guitars>
</guitars_catalog>

=== krissisavova/GuitarCatalog/GuitarsCatalog/Guitars-3.xml
<?xml version = "1.0" encoding = "UTF-8"?>

<?xml-stylesheet type="text/xsl" href="html-transformation-3.xsl"?>

<!DOCTYPE guitars_catalog SYSTEM "GuitarsCatalog.dtd">

<guitars_catalog>
    <guitars>
        <guitarAbout>
            <guitar>
                <brand> Fender Squier Affinity Series Stratocaster </brand>
                <image>fender-olympic-white.jpg</image>
            </guitar>
            <countryOfOrigin code="US" />
            <yearOfManufacture> 2015 </yearOfManufacture>
            <website> www.fender.com </website>
        </guitarAbout>

        <guitarAbout>
            <guitar>
                <brand> Ibanez Cosmic Shadow </brand>
                <image>ibanez-black.jpg</image>
            </guitar>
            <countryOfOrigin code="JP" />
            <yearOfManufacture> 2017 </yearOfManufacture>
            <website> www.ibanez.com </website>
        </guitarAbout>

        <guitarAbout>
            <guitar>
                <brand> Takamine GD51 Brown Sunburst </brand>
                <image>takamine.jpg</image>
            </guitar>
            <countryOfOrigin code="JP" />
            <yearOfManufacture> 2001 </yearOfManufacture>
            <website> www.takamine.com </website>
        </guitarAbout>

        <guitarAbout>
            <guitar>
                <brand> Framus FD Vintage </brand>
                <image>framus.jpg</image>
            </guitar>
            <countryOfOrigin code="DE" />
            <yearOfManufacture> 1995 </yearOfManufacture>
            <website> www.warwick.de или www.framus-vintage.de </website>
        </guitarAbout>

        <guitarAbout>
            <guitar>
                <brand> Sire Marcus Miller V5 Alder-5 Натурал </brand>
                <image>bass-sire.jpg</image>
            </guitar>
            <countryOfOrigin code="ID" />
            <yearOfManufacture> 2007 </yearOfManufacture>
            <website> www.sire-usa.com </website>
        </guitarAbout>

        <guitarAbout>
            <guitar>
                <brand> Arrow MH-10 Концертно укулеле Натурал </brand>
                <image>ukulele.jpg</image>
            </guitar>
            <countryOfOrigin code="JP" />
            <yearOfManufacture> 2018 </yearOfManufacture>
            <website> Няма информация </website>
        </guitarAbout>
    </guitars>
</guitars_catalog>

=== krissisavova/GuitarCatalog/GuitarsCatalog/Guitars-4.xml
<?xml version = "1.0" encoding = "UTF-8"?>

<?xml-stylesheet type="text/xsl" href="txt-transformation-2.xsl"?>

<!DOCTYPE guitars_catalog SYSTEM "GuitarsCatalog.dtd">

<guitars_catalog>
    <guitars>
        <productDetails isAvailable="Не">
            <guitar>
                <brand> Fender Squier Affinity Series Stratocaster </brand>
                <image> fender-olympic-white.jpg </image>
            </guitar>
            <series guitarId="037-8002-505" />
            <fingerboard_material> Клен </fingerboard_material>
            <amount> 0 </amount>
            <condition> Отлично </condition>
            <comingWith> калъф, колан за китара, перце </comingWith>
        </productDetails>

        <productDetails isAvailable="Да">
            <guitar>
                <brand> Ibanez Cosmic Shadow </brand>
                <image> ibanez-black.jpg </image>
            </guitar>
            <series guitarId="RG5320L-CSW" />
            <fingerboard_material> Черен абанос </fingerboard_material>
            <amount> 1 </amount>
            <condition> Отлично </condition>
        </productDetails>

        <productDetails isAvailable="Да">
            <guitar>
                <brand> Takamine GD51 Brown Sunburst </brand>
                <image> takamine.jpg </image>
            </guitar>
            <series guitarId="GD51-BSB" />
            <fingerboard_material> Лавър </fingerboard_material>
            <amount> 3 </amount>
            <condition> Много добро </condition>
            <comingWith> калъф, колан за китара, тунер, перце </comingWith>
        </productDetails>

        <productDetails isAvailable="Да">
            <guitar>
                <brand> Framus FD Vintage </brand>
                <image> framus.jpg </image>
            </guitar>
            <series guitarId="FR-FD-14-SV-VSNT-CL2" />
            <fingerboard_material> Махагон </fingerboard_material>
            <amount> 5 </amount>
            <condition> Много добро </condition>
            <comingWith> калъф, колан за китара </comingWith>
        </productDetails>

        <productDetails isAvailable="Да">
            <guitar>
                <brand> Sire Marcus Miller V5 Alder-5 Натурал </brand>
                <image> bass-sire.jpg </image>
            </guitar>
            <series guitarId="V5-ALDER-5-NT" />
            <fingerboard_material> Елша </fingerboard_material>
            <amount> 2 </amount>
            <condition> Отлично </condition>
            <comingWith> калъф, колан за китара, тунер </comingWith>
        </productDetails>

        <productDetails isAvailable="Да">
            <guitar>
                <brand> Arrow MH-10 Концертно укулеле Натурал </brand>
                <image> ukulele.jpg </image>
            </guitar>
            <series guitarId="ARROW-MH10" />
            <fingerboard_material> Махагон </fingerboard_material>
            <amount> 3 </amount>
            <condition> Отлично </condition>
        </productDetails>
    </guitars>
</guitars_catalog>
